name: Label Pull Request

on:
  pull_request:
    types: [opened, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and assign label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prTitle = context.payload.pull_request.title;
            const match = prTitle.match(/^Lab(\d+)/i);

            if (match) {
              const label = `Лаба${match[1]}`;

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });

              console.log(`Label "${label}" added.`);
            } else {
              console.log("No matching lab found in PR title.");
            }
